---@class sixelview.ImageConstraints
---@field min_width number?
---@field max_width number?
---@field min_height number?
---@field max_height number?

---@class sixelview.Options
---@field pattern string[]
---@field auto boolean
---@field delay_ms number
---@field constraints sixelview.ImageConstraints?
